env:
  global:
  - secure: DkLhgD/QO+NoKWauETkH01nWBDLXM+dYU5Ck12kMhOWHeoMjEdi7/RIDDyGH1F5Qc2XVIrNjIyQPpMmOXiH+28xuxATf6n8g1Q27Ttk9X4N4FwAofU88Ah6i3Pht7MuAlX44VTzOOX6uLbE/ydEWZ5AkdzhBx7s+VqVtUtQvPZ0=
language: java
install: "./etc/travis-setup.sh"
script: mvn clean install -Pit
after_script: heroku keys:remove $USER@`hostname`
