env:
  global:
  - secure: eTya5cZDDp13iXpTzcKih70YVfcxx2at3f4DVTMNzV2muU6KfoVKhxGUX/F8fLUzNjtLyqzHmtqkF2SHz3PpKDrD3vh23cTBNmm+RCEZh6+dQUEjiWeIWbEFI7XEVamYUiFnkdLZrbJBlpQF966+ME9/hbw/llng/aios/q1NEc=
language: java
install: "./etc/travis-setup.sh"
script: mvn clean install -Pintegration-test
after_script: heroku keys:remove $USER@`hostname`
