env:
  global:
  - secure: XI6bsMkwmMGMP3998jXG9pTdD1qfJWtyvVvLem7qDtmQepZ2dteGajJoRuKSoXOc3qjmY+VL0Bb51dSgtJDSzu5oHeRgXzl+g1fseL9tOHEDFAnc1syPn3payzq1vV8BQk3NsTWf42lBVqYZY7+PaeicBhbDLfqM0ujRDOwiqvI=
language: java
install: "./etc/travis-setup.sh"
script: mvn clean install -Pit
after_script: heroku keys:remove $USER@`hostname`
