env:
  global:
  - secure: jm/PZectIYmd+zxOfHKCerF2vd+oF7xov74mXcBcwBk9o7vpTEVStH9V1L/VE3Y7+a3tKQftD7dTC7spjtebvA1ZvBL0CuuHPHdhcsmFa6o3AvRPcxS16uEKYPjDPa8DwPRkS5PeS2/155MyC/DUNq8QZCIpoJOcXWtDlUnK4Xc=
language: java
install: "./etc/travis-setup.sh"
script: mvn clean install -Pintegration-test
after_script: heroku keys:remove $USER@`hostname`
