env:
  global:
  - secure: GE3Po4dnOHPgFDFuw5SFFUpnZhpSjWUu9wpKusTYSbAhihCkwzFiKzpitCCzOEopMRNVTTaGCTtGjjSSkK8ePLZeypfdn6DowQg4mtiVSSnRGmAiVbTLjXXdPUDV3FaH1A32dKODfHOY0EKo4k5Ius+22QEBHws0F3d0T4sHNIA=
language: java
install: "./etc/travis-setup.sh"
script: mvn clean install -Pintegration-test
after_script: heroku keys:remove $USER@`hostname`
